# Generated by Django 4.0.3 on 2022-03-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Inventor',
        ),
    ]
