# Generated by Django 4.0.3 on 2022-03-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_rename_inventory_inventor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventor',
            new_name='Inventory',
        ),
    ]
